import type { Metadata } from "next";
import DashboardLayout from "./dashboardWrapper";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from "next/font/google";
import MantineWrapper from "@/components/MantineWrapper";
import "@mantine/core/styles.css";
import "mantine-datatable/styles.layer.css";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} flex min-h-full flex-col`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          storageKey="arsenal-theme"
        >
          <MantineWrapper>
            <DashboardLayout>{children}</DashboardLayout>
          </MantineWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
